# REWARD_GATE = 500
# REWARD_DISTANCE_REDUCTION = 2
# PENALTY_DISTANCE_INCREASE = 7
# REWARD_CIRCUIT_COMPLETION = 10000
REWARD_TIMESTEP = -1

REWARD_WRONG_MOVE = 100000
REWARD_NON_ZEROS = 0.5

DEVICE = 'cpu'
